name: Pull Request Stats

on:
  pull_request:
    types: [closed]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: wooclap/pr-stats@v0.2.0
        with:
          comment: true
