name: Pull Request Stats

on:
  pull_request:
    types: [closed]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: manzan46/pr-stats@v0.1.0
        with:
          comment: true
